### PR TITLE
Begin work for Py3 Compatibility

### PR DESCRIPTION
**Pull request by Tikipeter**
This is a start to the work for compatibility for Python 3.
In this pull request, changed py2-3 imports have been fixed on OS's modules.

This is NOT a complete fix for Python 3 compatibility. It is only the first step.
Other needed steps:
* Fix all imports on all scrapers.
* Fix any references to encode/decode for modules and scrapers.
* Any other fixes needed.

IT IS NOT EXPECTED THAT OPEN SCRAPERS WILL RUN ON PYTHON 3 WITH THIS PULL REQUEST. IT IS A START ALONG THE WAY TO THAT.

The important thing to look for at the moment is that these changes do not affect OS for Python 2.

### CODE REVIEW

**Comment by goceti** [comment]
https://github.com/PythonCharmers/python-future/blob/master/src/future/standard_library/__init__.py#L465

Great job but I think for these kinds of stuff you might be better off with something like this. That'll save you the work to remove the Py2 stuff from all the scripts when dropping support for Py2 some day.

**Comment by goceti** [comment]
Not sure what you mean by "OS being stuck" but what I meant was just that you could copy those lines to rename the Py2 urllib to the Py3 urllib. You don't need to use the whole future lib.

**Comment by Tikipeter** [comment]
Which lines?

**Comment by drinfernoo** [comment]
@Tikipeter He's referring to the lines he linked, which are importing `futures` versions of `urllib`. Your solution is fine.

**Comment by goceti** [comment]
```
import urllib
import urlparse
urlparse.urlencode = urllib.urlencode
sys.modules['urllib.parse'] = urlparse
```

This is what I mean. You could then use urllib.parse.urljoin and urllib.parse.urlencode etc. throughout the whole codebase instead of doing that import try catch thingy in every file.

**Comment by drinfernoo** [comment]
@goceti The "import try catch thingy" you're referring to is the generally accepted method of dealing with this situation.

**Comment by goceti** [comment]
I never said it was wrong. I just proposed an alternative, easier way.

The maybe best option might be to use the Python `requests` module for http requests. You could then also use `requests.compat` for stuff like urljoin, urlencode and so on, if needed.

https://github.com/psf/requests/blob/master/requests/compat.py

**Comment by Tikipeter** [comment]
I'll cancel this pull request and I will redo it after the fresh Openscrapers update from Ken.

**Pull request closed without merging**
