### PR TITLE
Add PubFilmOnline.ws scraper

### PR DESCRIPTION
**Pull request by TheDevFreak**
Also removes `lib/` from the gitignore, because otherwise it's ignoring the directory of the module essentially...

### CODE REVIEW

**Comment by host505** [comment]
Hey, thanks for the scrapers.
But may I ask, why you set `self.priority = 0`? That parameter, when set to 0, has the potential to ignore the user's scraping timeout setting, and if the scraper breaks or is too slow it can delay the scraping proccess too much.

**Comment by TheDevFreak** [comment]
@host505 I'm not sure, that was just the default in the base plate I used; what should I change it to? 1?

**Comment by host505** [comment]
1 is the norm. It can either be 0 or 1, 0 does what I described above.
The parameter was added back then, when some (considered by the original creator) essential scrapers where a bit slow, but it should be used with caution.

**Comment by TheDevFreak** [comment]
@host505 just updated it :)

**Comment by host505** [comment]
You're great, keep'em coming!

**Comment by A4K-Official** [comment]
Ty guys :) loving all the collaboration going on!

**Pull request merged**
