### PR TITLE
Scraper fixes/adjustments

### PR DESCRIPTION
**Pull request by host505**
See commit titles

### CODE REVIEW

**Comment by A4K-Official** [comment]
cfscrape in dev branch is latest version also could you resolve the conflicts so i may merge then :)

**Comment by host505** [comment]
Oh fuckit. You can see the changes, if you want make them.

**Comment by nazegnl** [comment]
I think this PR was a good one. We should only test and see which of the scrapers is better.

**Comment by A4K-Official** [comment]
already tested as an internal guy was funnily enough working on the same stuff when @host505 PRd it lol and okay @host505 i already incorporated all your changes :) thanks sorry for the merges lol

**Comment by host505** [comment]
You still got filmxy wrongly spelt on defaults.py lol.
scnsrc isn't a broken scraper, but it's very slow, it sometimes brings (hell of a lot of) results on the 2nd scrape attempt.
You also forgot 123123movies scraper

**Comment by A4K-Official** [comment]
the hell lol i added all of those! ugh mustve fucked something up on my end lol doing again! grrr

**Comment by A4K-Official** [comment]
lmfao flimxy instead of filmxy haha

**Comment by A4K-Official** [comment]
done now

**Comment by host505** [comment]
Thanks, but filmxy still won't work like that, has some faults. Don't know why you alter and break the code I send you :) This works:
https://raw.githubusercontent.com/host505/script.module.openscrapers/develop/lib/openscrapers/sources_openscrapers/en/filmxy.py

Btw quality identification is a bit shitte for that scraper, and it's a shame because it's a good one, for both free and debrid links. Can anyone have a look?

**Pull request closed without merging**
