### PR TITLE
Merged master back into develop

### PR DESCRIPTION
**Pull request by nazegnl**

### CODE REVIEW

**Comment by A4K-Official** [comment]
great PR :D ty merging :)

**Comment by A4K-Official** [comment]
@nazegnl crap i shouldve looked at changed files before merge regarding iwaatch, arent those the same merge errors you listed out to me previously? just making sure

**Comment by nazegnl** [comment]
Will have a look

**Comment by A4K-Official** [comment]
thanks other than that the merge was good it looks like :) ty for all the help recently. im honestly still learning in this stuff, im not really a coder or anything but im mosly managing this and figuring this out as i go. been interesting to say the least haha

**Pull request merged**
