### PR TITLE
Enabled loggin of module loading errors with optional debug parameter

### PR DESCRIPTION
**Pull request by nazegnl**

### CODE REVIEW

**Comment by A4K-Official** [comment]
im gonna have to add a hidden setting for torrent.enabled in settings.xml for that new debrid.py im guessing just do see a point of having it visual lol

**Comment by nazegnl** [comment]
Exodusredux had it in its settings.bit could be nice if it works with both settings pages.

**Comment by A4K-Official** [comment]
Not going to happen as i want OpenScrapers to standalone unless there's a way for another add-on to directly read and change another add-ons settings? Would make it easier for the front end developers

**Comment by bjbca** [comment]
Well after properly importing Openscrapers to an addon in addon.xml and sources.py then this code in the addons settings.xml is all that is needed isnt it ?    
<category label="32345">
        <setting label="English" type="lsep" />
        <setting type="sep" />
        <setting id="open.settings" type="action" label="Open Scrapers Settings" option="close" action="RunPlugin(plugin://script.module.openscrapers/?mode=OpenscrapersSettings)" />
    </category>

**Pull request merged**
