### PR TITLE
Updated cache module and source_utils

### PR DESCRIPTION
**Pull request by sraedler**
Changed caching method to pickle dump and added additional parameters. This enables the module to cache any type of data. This is especially helpful to use the cache module for cfscrape requests.

In the source_utils, a function is added to create a distinct search array from title, localtitle and aliases.

### CODE REVIEW

**Comment by sraedler** [comment]
> This project is in hopes to unify the community and contribute to one scraper pack for multi scraper add-ons and not having the repo go dead or disappear. 

Yeah, this Pull Request show, that the project is also not how the communities are going to come together and work on one base. If no maintainer even reply after more than a week, than it's not motivating to contribute.

**Comment by drinfernoo** [comment]
@sraedler Considering that this is a relatively small open source project with few contributors and maintainers to have gotten the ball rolling and keep it that way, and that, to my knowledge, nobody that has had any involvement in this project has made it their full time job yet... it's not unreasonable to assume that after a week something might go unlooked at.

The main Kodi project in GitHub has issues and pull requests that have been open for weeks or months, for goodness sakes.

**Comment by reddit-reaper** [comment]
@sraedler sorry about that i never got the email about this PR so never checked. Will look into also there's going to be some branch conflicts as we had updated somethings these last few days

**Comment by sraedler** [comment]
Sorry for being not respectful enough to you. I just thought you saw it and don‘t care about external contributions.

I would recommend to use the issue tracker, because otherwise things are done twice and there will never be more developers...

And my last cent: I would love, if you could use the develop branch as its name. Because contributions are than more easy. I would really like to contribute from time to time...

If you have questions about the PR, please ask!

**Comment by sraedler** [comment]
@reddit-reaper I think my PR is suitable for your changes as well

**Comment by reddit-reaper** [comment]
Better yet, message me on Reddit. Reddit_reaper.

**Comment by nazegnl** [comment]
@reddit-reaper and @sraedler We need to be careful by using pickle, because the py2.7 pickle is alot slower and should nog be used. If we can use cPickle this is alot faster on py2. In py3 the pickle import uses cPickle if enabled in the python distribution. 

I'm not sure if all supported platforms support cPickle, we need testing to confirm this will work on Android for example.

**Comment by sraedler** [comment]
@reddit-reaper I sent you a message on reddit
@nazegnl You are right. Since Picle is available on Android, a try catch import might be an option

**Comment by nazegnl** [comment]
@sraedler I think regular pickle for py2 is out of the question. We need cPickle else performance will be bad.

**Comment by sraedler** [comment]
@nazegnl I ment something like 
```
try: import cPickle as pickle
except: import Pickle as pickle
```

**Pull request closed without merging**
