### PR TITLE
Fixed library.py | RLSBB.py | Seizonlukdizi.py

### PR DESCRIPTION
**Pull request by nazegnl**

### CODE REVIEW

**Comment by bjbca** [comment]
Funny thing I just tried the rlsbb and sezonlukdizi from OS v 0.0.0.5 and they worked, i ran them in OS v 0.0.1.6

**Comment by nazegnl** [comment]
@bjbca  Thnx for testing :) fixed both of them if you have more suggestions keep them comming !

**Comment by bjbca** [comment]
;)

**Comment by bjbca** [comment]
hi, the new rlsbb gets nothing for me so i put the old one back and i get lots, the sezlon gets verry little with old and new, i did use the new dev cache for this test, thnx ;)

**Comment by A4K-Official** [comment]
You know it's weird because the old one never worked for me lol

**Comment by A4K-Official** [comment]
Want to join our discord and be an official tester? :)

**Comment by bjbca** [comment]
thank you but im just putting time in when i can so if we could carry on as
is it works for me ;)
Also can i share the rlsbb code that works for me in this thread ?

**Comment by bjbca** [comment]
so here are the files im using, rlsbb works well, im using kodi 18.2 on a macbook pro, and i use my modded version of exodus 801/318, it is modded to work with openscrapers and resolveurl and does not have indigo and repos etc and can clear all caches, i have modded openscrapers to not have any settings other than enable all, disable all, torrents disabled and debug log, and all the scrapers i use get put in the en folder, this way there are no settings glitches.
[rlsbb.sezonlukdizi.zip](https://github.com/a4k-openproject/script.module.openscrapers/files/3175434/rlsbb.sezonlukdizi.zip)

**Comment by nazegnl** [comment]
@bjbca we are having issue with the cloudflare anti bit protection. 1 out of 5 attempts would yield results only.

Can you try and run the solution with the test script included in the repo this would greatly engNce your testing and debugging capabilities.

**Comment by bjbca** [comment]
k, i will look at the script more maybe tonight, having trouble configing it right getting syntax errors, running on mac using idle app

**Comment by nazegnl** [comment]
@bjbca  Make sure you are using the 2.7 version of python when running the test script.

**Comment by bjbca** [comment]
Ok, im doing something wrong, of course i do have the module named requests in kodi addons but...

Python 2.7.16 (v2.7.16:413a49145e, Mar  2 2019, 14:32:10) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: /Users/xxxx/Library/Application Support/Kodi/addons/script.module.openscrapers/scrape-test.py 

Traceback (most recent call last):
  File "/Users/xxxxx/Library/Application Support/Kodi/addons/script.module.openscrapers/scrape-test.py", line 8, in <module>
    import requests
ImportError: No module named requests
>>>

**Comment by A4K-Official** [comment]
You need to install python requests and bs4

**Comment by bjbca** [comment]
ok, i have bs4 guess i will get requests, thnx

**Comment by bjbca** [comment]
Ok here are some tests... sorry i have all my En and Debrid scrapers in 1 folder so the csv's dont reflect debrid only, next time i will set up the folders. i have provided the csv's and 2 pdf's made from python output window of Movie and Episode testing
[Episode.test.May.14.zip](https://github.com/a4k-openproject/script.module.openscrapers/files/3180785/Episode.test.May.14.zip)
[Movie.Episode.Py.pdf.zip](https://github.com/a4k-openproject/script.module.openscrapers/files/3180786/Movie.Episode.Py.pdf.zip)
[Movie.test.May.14.zip](https://github.com/a4k-openproject/script.module.openscrapers/files/3180787/Movie.test.May.14.zip)

**Comment by bjbca** [comment]
It would be cool if we could script scrapetest py to search a particular show, for instance when i run scrape tests for episodes then certain shows from trakt lists are scraped and then the old rlsbb doesnt return anything but if i do a search in kodi for a particular show/episode then i get lots of links, I attached an example here:
Screen Shot 2019-05-15 at 6 51 07 PM
Screen Shot 2019-05-15 at 6 54 18 PM

**Comment by nazegnl** [comment]
@bjbca yes, there is still an issue with the anti not page of cloudflare. This explains the behaviour you are seeing now. 1 out of 5 attempts is getting through to the actual site.
There are slot of variables that make it succeed or not.

**Pull request merged**
