### PR TITLE
Update/fix some torr scrapers to match your new debrid.py

### PR DESCRIPTION
**Pull request by host505**

### CODE REVIEW

**Comment by nazegnl** [comment]
:)

**Comment by A4K-Official** [comment]
@host505 mind fixing conflicts, made some changes prior to your PR being merged

**Comment by host505** [comment]
No need to, changes I made have been addressed on your commit.
Btw the 2dll scraper you added is for the same site as the invictus one, maybe ditch it or you're double scraping it.
And that skytorrents torr scraper, breaks scraping on my end. Works if I disable it.

**Comment by A4K-Official** [comment]
Will look at when i get back home and thanks

**Pull request closed without merging**
