### PR TITLE
Develop merge

### PR DESCRIPTION
**Pull request by reddit-reaper**

### CODE REVIEW

**Comment by host505** [comment]
"disable"??
"bool" type settings can either be  "true" or "false"

**Comment by reddit-reaper** [comment]
Facepalm crap.... Will fix in a bit

**Comment by host505** [comment]
Well there's no actual harm done, because when set to 'disable' it just takes it as invalid and disables the scraper :)

**Comment by 123Venom** [comment]
@reddit-reaper you set a bool default="disable"? you turkey you know better...lol

**Comment by reddit-reaper** [comment]
fixed lol sorry xD @host505 btw check your reddit messages lol

**Pull request merged**
