### PR TITLE
More stuff

### PR DESCRIPTION
**Pull request by nazegnl**

### CODE REVIEW

**Comment by A4K-Official** [comment]
ok before i jump the gun this time lol so we're not going to use this one from @host505 anymore?

https://raw.githubusercontent.com/host505/script.module.openscrapers/develop/lib/openscrapers/sources_openscrapers/en/filmxy.py

he said source quality identification isn't the greatest and if it was possible to get better. any comments on that?

**Comment by nazegnl** [comment]
I used his scraper and added the cfscrape ontop. They use CF for their domain stuf so the change could be there that they enable the ddos protection. This way we are prepared,

**Comment by nazegnl** [comment]
Alos added some more functionality to the test script that dumps all the links to csv so you can check actually what the scraper is producing.

**Comment by A4K-Official** [comment]
oh was going to mention to you, test_type in scrape-test isnt working last i used it, would always do 1 even if i set 0, and your CSV export you had changed it to semicolon instead of comma so the csv was all messed up. did you get that fixed already? so many commits so not sure lol

**Comment by nazegnl** [comment]
With me the test_mode option is working perfectly and can test the scrapers seperatly. Also reverteted the semicolon change.

**Comment by A4K-Official** [comment]
ok thanks this was a few updates ago and havent tested since so just making sure. will merge changes then

**Pull request merged**
