### PR TITLE
Cleanup and added 4K to the solution

### PR DESCRIPTION
**Pull request by nazegnl**

### CODE REVIEW

**Comment by reddit-reaper** [comment]
hey sorry i saw this way late and you had modified an older version of scraper tester. might want to look at the latest one. i merged changes though best i could trying to resolve the conflicts lol

**Comment by reddit-reaper** [comment]
@nazegnl hey i had to revert your changes to DirectDL, well to the scraper i got from Venom's addon. DirectDL scraper wouldnt work with those source_utils additions you made. Can you re-check it please

**Comment by nazegnl** [comment]
Sorry just noticed your message now I don't know if this is still applicable?

**Comment by A4K-Official** [comment]
Well i had changed the scraper anyways so not exactly but would be cool if it worked with your changes

**Comment by A4K-Official** [comment]
Have you seen my other messages?

**Pull request merged**
